import React, { createContext, useState, useContext } from "react";

export type Language = "en" | "ta" | "hi" | "as" | "bn" | "gu" | "kn" | "ml" | "mr" | "or" | "pa" | "te";

interface LanguageContextType {
  language: Language;
  selectedLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tText: (en: string, ta?: string, hi?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.practiceAreas": "Practice Areas",
    "nav.associates": "Associates",
    "nav.caseResults": "Case Results",
    "nav.insights": "Insights",
    "nav.aboutUs": "About Us",
    "nav.contactUs": "Contact Us",
    "nav.bookConsultation": "Book Consultation",
    "nav.allPractice": "All Practice Areas",
    "nav.attorneys": "Attorneys",

    // Home Hero
    "hero.badge": "Premier Legal Consultancy & Advocacy",
    "hero.title1": "Authority. Integrity.",
    "hero.title2": "Uncompromising Results.",
    "hero.desc": "Araththaai (AKM Associates) represents corporations, startups, and families through complex jurisdictions. We deliver high-stakes courtroom victories and comprehensive compliance structures.",
    "hero.btnIntake": "Schedule Privileged Intake",
    "hero.btnExplore": "Explore Practice Areas",

    // Home Statistics
    "stats.exp.val": "11+",
    "stats.exp.lbl": "Years Active Experience",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "Favorable Settlements",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "Corporate & Private Clients",
    "stats.credentials.val": "Top Tier",
    "stats.credentials.lbl": "Legal Bar Credentials",

    // Home Sections
    "home.practice.badge": "Specialized Jurisdictions",
    "home.practice.title": "Practice Areas",
    "home.practice.desc": "Our firm balances corporate governance advisory, land title audit investigations, and trial defense advocacy at premium standards.",
    "home.practice.all": "View All Practice Areas",
    
    "home.team.badge": "Elite Counsel",
    "home.team.title": "Spotlight Partners",
    "home.team.desc": "Dedicated advocates combining specialized knowledge and decades of trial experience.",
    "home.team.viewProfile": "View Profile",
    "home.team.all": "Meet All Attorneys",

    "home.testimonials.badge": "Client Feedback",
    "home.testimonials.title": "Trusted by Leaders",
    
    // Contact Info
    "contact.badge": "Our Legal Services",
    "contact.title": "Expertise That Matters",
    "contact.office": "Branch Offices & Helpline",
    "contact.officeDesc": "Inquiries are treated with strict confidentiality under professional lawyer codes. Access our direct offices or contact our emergency desk.",
    "contact.branchChennai": "Headquarters (Chennai Office)",
    "contact.branchKarur": "Branch Office (Karur Office)",
    "contact.helpline": "Emergency Legal Helpline",
    "contact.helplineDesc": "Direct access for bails & immediate custody issues (24/7)",
    "contact.email": "Email Inquiries",
    "contact.hours": "Office Hours",
    "contact.hoursWeek": "Monday - Friday: 9:00 AM - 7:00 PM",
    "contact.hoursSat": "Saturday: 10:00 AM - 2:00 PM (Appts Only)",
    "contact.formTitle": "Send a Privileged Inquiry",
    "contact.name": "Full Name",
    "contact.emailAddr": "Email Address",
    "contact.phone": "Phone Number",
    "contact.message": "Message / Case Details",
    "contact.btnSend": "Send Privileged Inquiry",
    "contact.successTitle": "Inquiry Sent Successfully",
    "contact.successDesc": "Your message has been encrypted and delivered. A senior partner will contact you directly within 24 business hours.",
    "contact.btnAnother": "Send another message",

    // Footer
    "footer.desc": "Araththaai (AKM Associates) is a premier legal consultancy and advocacy firm representing corporations, institutions, and individuals.",
    "footer.contact": "Contact Info",
    "footer.rights": "All rights reserved.",
    "footer.disclaimerTitle": "Attorney Advertising Disclaimer:",
    "footer.disclaimerText": "Under rules of professional conduct in certain jurisdictions, contents on this site may be considered attorney advertising. Prior outcomes achieved do not guarantee similar results. Consultation bookings do not constitute a binding attorney-client relationship.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.disclaimer": "Disclaimer",
  },
  ta: {
    // Navbar
    "nav.home": "முகப்பு",
    "nav.practiceAreas": "சட்டப் பிரிவுகள்",
    "nav.associates": "வழக்கறிஞர்கள்",
    "nav.caseResults": "வழக்கு முடிவுகள்",
    "nav.insights": "சட்டக் கட்டுரைகள்",
    "nav.aboutUs": "எங்களைப் பற்றி",
    "nav.contactUs": "தொடர்புகொள்ள",
    "nav.bookConsultation": "ஆலோசனை பதிவு",
    "nav.allPractice": "அனைத்து சட்டப் பிரிவுகள்",
    "nav.attorneys": "வழக்கறிஞர்கள்",

    // Home Hero
    "hero.badge": "முதன்மை சட்ட ஆலோசனை & வாதாடுதல்",
    "hero.title1": "அதிகாரம். நேர்மை.",
    "hero.title2": "சமரசமற்ற முடிவுகள்.",
    "hero.desc": "அறத்தாய் (AKM அசோசியேட்ஸ்) நிறுவனங்கள், ஸ்டார்ட்-அப்கள் மற்றும் குடும்பங்களின் சிக்கலான சட்ட விவகாரங்களை கையாள்கிறது. நாங்கள் நீதிமன்ற வெற்றிகளையும் முழுமையான சட்ட ஆலோசனைகளையும் வழங்குகிறோம்.",
    "hero.btnIntake": "ஆலோசனை பெற",
    "hero.btnExplore": "சட்டப் பிரிவுகளை ஆராய்க",

    // Home Statistics
    "stats.exp.val": "11+",
    "stats.exp.lbl": "வருடங்கள் நேரடி அனுபவம்",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "சாதகமான தீர்வுகள்",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "நிறுவனங்கள் & தனிநபர் வாடிக்கையாளர்கள்",
    "stats.credentials.val": "உயர்தர",
    "stats.credentials.lbl": "சட்டச் சான்றுகள்",

    // Home Sections
    "home.practice.badge": "சிறப்பு சட்டப்பிரிவுகள்",
    "home.practice.title": "சட்டப் பிரிவுகள்",
    "home.practice.desc": "எங்கள் நிறுவனம் கார்ப்பரேட் ஆளுமை ஆலோசனை, நிலப் பத்திர சரிபார்ப்புகள் மற்றும் நீதிமன்ற வழக்கு வாதங்களை உயர்தரத்தில் வழங்குகிறது.",
    "home.practice.all": "அனைத்து சட்டப் பிரிவுகளையும் காண்க",
    
    "home.team.badge": "சிறந்த வழக்கறிஞர்கள்",
    "home.team.title": "முக்கிய பங்குதாரர்கள்",
    "home.team.desc": "சிறப்பு அறிவும் பல வருட வழக்கு அனுபவமும் கொண்ட அர்ப்பணிப்புள்ள வழக்கறிஞர்கள்.",
    "home.team.viewProfile": "விவரம் காண்க",
    "home.team.all": "அனைத்து வழக்கறிஞர்களையும் சந்திப்பு செய்ய",

    "home.testimonials.badge": "வாடிக்கையாளர் கருத்துக்கள்",
    "home.testimonials.title": "தலைவர்களின் நம்பிக்கை",
    
    // Contact Info
    "contact.badge": "எங்கள் சட்ட சேவைகள்",
    "contact.title": "முக்கியமான சட்ட நிபுணத்துவம்",
    "contact.office": "கிளை அலுவலகங்கள் & உதவி எண்",
    "contact.officeDesc": "அனைத்து விசாரணைகளும் வழக்கறிஞர் விதிகளின் கீழ் கடுமையான ரகசியத்தன்மையுடன் கையாளப்படுகின்றன. எங்களை நேரடியாகவோ அல்லது அவசர உதவி எண் மூலமாகவோ தொடர்பு கொள்ளவும்.",
    "contact.branchChennai": "தலைமையகம் (சென்னை அலுவலகம்)",
    "contact.branchKarur": "கிளை அலுவலகம் (கரூர் அலுவலகம்)",
    "contact.helpline": "அவசர சட்ட உதவி எண்",
    "contact.helplineDesc": "ஜாமீன் & அவசர சட்டப் பிரச்சனைகளுக்கான நேரடித் தொடர்பு (24/7)",
    "contact.email": "மின்னஞ்சல் தொடர்புகள்",
    "contact.hours": "அலுவலக நேரங்கள்",
    "contact.hoursWeek": "திங்கள் - வெள்ளி: காலை 9:00 - மாலை 7:00",
    "contact.hoursSat": "சனி: காலை 10:00 - மதியம் 2:00 (முன்பதிவு மட்டும்)",
    "contact.formTitle": "சட்ட ஆலோசனைக்கு செய்தி அனுப்பவும்",
    "contact.name": "முழு பெயர்",
    "contact.emailAddr": "மின்னஞ்சல் முகவரி",
    "contact.phone": "தொலைபேசி எண்",
    "contact.message": "செய்தி / வழக்கு விவரங்கள்",
    "contact.btnSend": "செய்தி அனுப்புக",
    "contact.successTitle": "செய்தி வெற்றிகரமாக அனுப்பப்பட்டது",
    "contact.successDesc": "உங்கள் செய்தி பாதுகாப்பாக அனுப்பப்பட்டது. எங்கள் மூத்த வழக்கறிஞர் ஒருவர் 24 மணி நேரத்திற்குள் உங்களைத் தொடர்புகொள்வார்.",
    "contact.btnAnother": "மறுபடி செய்தி அனுப்ப",

    // Footer
    "footer.desc": "அறத்தாய் (AKM அசோசியேட்ஸ்) என்பது நிறுவனங்கள், அமைப்புகள் மற்றும் தனிநபர்களைப் பிரதிநிதித்துவப்படுத்தும் ஒரு முன்னணி சட்ட ஆலோசனை மற்றும் வாதாடும் நிறுவனமாகும்.",
    "footer.contact": "தொடர்பு விபரங்கள்",
    "footer.rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    "footer.disclaimerTitle": "வழக்கறிஞர் விளம்பர மறுப்புரை:",
    "footer.disclaimerText": "சில சட்ட வரம்புகளில் உள்ள தொழில்முறை நடத்தை விதிகளின் கீழ், இந்த தளத்தின் உள்ளடக்கங்கள் வழக்கறிஞர் விளம்பரமாகக் கருதப்படலாம். முந்தைய வழக்கு முடிவுகள் தற்போதைய முடிவுகளுக்கு உத்தரவாதம் அளிக்காது. ஆலோசனை முன்பதிவுகள் வழக்கறிஞர்-வாடிக்கையாளர் உறவை உருவாக்காது.",
    "footer.privacy": "தனியுரிமைக் கொள்கை",
    "footer.terms": "சேவை விதிமுறைகள்",
    "footer.disclaimer": "பொறுப்புத் துறப்பு",
  },
  hi: {
    // Navbar
    "nav.home": "होम",
    "nav.practiceAreas": "कार्यक्षेत्र",
    "nav.associates": "सहयोगी वकील",
    "nav.caseResults": "मामलों के परिणाम",
    "nav.insights": "लेख एवं अंतर्दृष्टि",
    "nav.aboutUs": "हमारे बारे में",
    "nav.contactUs": "संपर्क करें",
    "nav.bookConsultation": "परामर्श बुक करें",
    "nav.allPractice": "सभी कानूनी क्षेत्र",
    "nav.attorneys": "वकील",

    // Home Hero
    "hero.badge": "प्रमुख कानूनी परामर्श और वकालत",
    "hero.title1": "प्राधिकार। सत्यनिष्ठा।",
    "hero.title2": "सार्थक परिणाम।",
    "hero.desc": "अरथाई (एकेएम एसोसिएट्स) कॉर्पोरेट्स, स्टार्टअप्स और परिवारों का जटिल कानूनी क्षेत्रों में प्रतिनिधित्व करता है। हम अदालत में सफलता और व्यापक अनुपालन ढांचा प्रदान करते हैं।",
    "hero.btnIntake": "गोपनीय परामर्श बुक करें",
    "hero.btnExplore": "कार्यक्षेत्र देखें",

    // Home Statistics
    "stats.exp.val": "11+",
    "stats.exp.lbl": "वर्षों का सक्रिय अनुभव",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "सकारात्मक समाधान",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "कॉर्पोरेट और निजी क्लाइंट",
    "stats.credentials.val": "सर्वोच्च श्रेणी",
    "stats.credentials.lbl": "बार एसोसिएशन प्रमाण-पत्र",

    // Home Sections
    "home.practice.badge": "विशेष कानूनी क्षेत्र",
    "home.practice.title": "कानूनी कार्यक्षेत्र",
    "home.practice.desc": "हमारी फर्म कॉर्पोरेट प्रशासन, भूमि स्वामित्व ऑडिट और अदालत में वकालत को उच्च मानकों पर संतुलित करती है।",
    "home.practice.all": "सभी कार्यक्षेत्र देखें",
    
    "home.team.badge": "उत्कृष्ट वकील",
    "home.team.title": "मुख्य भागीदार",
    "home.team.desc": "विशेषज्ञ ज्ञान और दशकों के अदालती अनुभव वाले समर्पित वकील।",
    "home.team.viewProfile": "प्रोफ़ाइल देखें",
    "home.team.all": "सभी वकीलों से मिलें",

    "home.testimonials.badge": "क्लाइंट प्रतिक्रिया",
    "home.testimonials.title": "नेताओं का भरोसा",
    
    // Contact Info
    "contact.badge": "हमारी कानूनी सेवाएं",
    "contact.title": "महत्वपूर्ण विशेषज्ञता",
    "contact.office": "शाखा कार्यालय और हेल्पलाइन",
    "contact.officeDesc": "व्यावसायिक वकील नियमों के तहत सभी पूछताछ पूरी तरह से गोपनीय रखी जाती हैं। हमारे कार्यालयों में आएं या तत्काल सहायता लें।",
    "contact.branchChennai": "मुख्यालय (चेन्नई कार्यालय)",
    "contact.branchKarur": "शाखा कार्यालय (करूर कार्यालय)",
    "contact.helpline": "आपातकालीन कानूनी हेल्पलाइन",
    "contact.helplineDesc": "जमानत और तत्काल पुलिस हिरासत के मामलों के लिए सीधा संपर्क (24/7)",
    "contact.email": "ईमेल संपर्क",
    "contact.hours": "कार्यालय का समय",
    "contact.hoursWeek": "सोमवार - शुक्रवार: सुबह 9:00 - शाम 7:00",
    "contact.hoursSat": "शनिवार: सुबह 10:00 - दोपहर 2:00 (केवल अपॉइंटमेंट)",
    "contact.formTitle": "गोपनीय पूछताछ भेजें",
    "contact.name": "पूरा नाम",
    "contact.emailAddr": "ईमेल पता",
    "contact.phone": "फ़ोन नंबर",
    "contact.message": "विवरण / मामले की जानकारी",
    "contact.btnSend": "पूछताछ भेजें",
    "contact.successTitle": "पूछताछ सफलतापूर्वक भेजी गई",
    "contact.successDesc": "आपका संदेश सुरक्षित रूप से भेज दिया गया है। हमारे एक वरिष्ठ भागीदार 24 व्यावसायिक घंटों के भीतर आपसे सीधे संपर्क करेंगे।",
    "contact.btnAnother": "दूसरा संदेश भेजें",

    // Footer
    "footer.desc": "अरथाई (एकेएम एसोसिएट्स) कॉर्पोरेट्स, संस्थानों और व्यक्तियों का प्रतिनिधित्व करने वाली एक अग्रणी कानूनी परामर्श और वकालत फर्म है।",
    "footer.contact": "संपर्क जानकारी",
    "footer.rights": "सर्वाधिकार सुरक्षित।",
    "footer.disclaimerTitle": "वकील विज्ञापन अस्वीकरण:",
    "footer.disclaimerText": "कुछ न्यायक्षेत्रों में पेशेवर आचरण नियमों के तहत, इस साइट की सामग्री को वकील विज्ञापन माना जा सकता है। पिछले मामले के परिणाम भविष्य के परिणामों की गारंटी नहीं देते हैं। परामर्श बुकिंग से कोई कानूनी वकील-क्लाइंट संबंध नहीं बनता है।",
    "footer.privacy": "गोपनीयता नीति",
    "footer.terms": "सेवा की शर्तें",
    "footer.disclaimer": "अस्वीकरण",
  },
  as: {
    "nav.home": "મુખ્ય પૃષ્ઠ",
    "nav.practiceAreas": "আইনী ক্ষেত্ৰসমূহ",
    "nav.associates": "सहयोगी वकील",
    "nav.caseResults": "গোচৰৰ ফলাফল",
    "nav.insights": "प্ৰবন্ধ আৰু ব্লগ",
    "nav.aboutUs": "আমাৰ বিষয়ে",
    "nav.contactUs": "যোগাযোগ কৰক",
    "nav.bookConsultation": "পৰামৰ্শ বুক কৰক",
    "nav.allPractice": "সকলো আইনী ক্ষেত্ৰ",
    "nav.attorneys": "অধিবক্তাসকল",
    "hero.badge": "প্ৰিমিয়াৰ আইনী পৰামৰ્শ আৰু ওকালতি",
    "hero.title1": "কর্তৃত্ব। সততা।",
    "hero.title2": "আপোচহীন ফলাফল।",
    "hero.desc": "আৰাথাই (এ কে এম এছ'চিয়েটচ)-এ জটিল ন্যায়িক অধিকাৰক্ষেত্ৰৰ জৰিয়তে নিগম, ষ্টাৰ্টআপ, আৰু পৰিয়ালসমূহক প্ৰতিনিধিত্ব কৰে। আমি উচ্চ-বাজিৰ আদালতৰ কক্ষৰ জয় আৰু ব্যাপক অনুসৰণ কাঠামো প্ৰদান কৰোঁ।",
    "hero.btnIntake": "পৰামৰ্শৰ সময়সূচী নিৰ্ধাৰণ কৰক",
    "hero.btnExplore": "আইনী ক্ষেત্ৰসমূহ অন্বেষণ কৰক",
    "stats.exp.val": "১১+",
    "stats.exp.lbl": "বছৰৰ সক্ৰিয় অভিজ্ঞতা",
    "stats.settle.val": "৯৮%",
    "stats.settle.lbl": "অনুকূল সমাধান",
    "stats.clients.val": "৫,০০০+",
    "stats.clients.lbl": "কৰ্পোৰেট আৰু ব্যক্তিগত ক্লায়েন্ট",
    "stats.credentials.val": "উচ্চ শ্ৰেণী",
    "stats.credentials.lbl": "আইনী বাৰ প্ৰমাণপত্ৰ",
    "home.practice.badge": "विशेष আইনী ক্ষেত্ৰ",
    "home.practice.title": "আইনী ক্ষেত্ৰসমূহ",
    "home.practice.desc": "আমাৰ ফাৰ্মে কৰ্পোৰেট শাসন, ভূমি স্বত্ব অডিট আৰু আদালতত ওকালতি উচ্চ মানদণ্ডত সন্তুলিত কৰে।",
    "home.practice.all": "সকলো আইনী ক্ষেত্ৰ কঢ়িয়াওক",
    "home.team.badge": "অভিজ্ঞ অধিবক্তা",
    "home.team.title": "মুখ্য অংশীদাৰসকল",
    "home.team.desc": "বিশেষ জ্ঞান আৰু দশকৰ আদালতৰ অভিজ্ঞতা থকা উৎসৰ্গীকৃত অধিবক্তাসকল।",
    "home.team.viewProfile": "প্ৰফাইল চাওক",
    "home.team.all": "সকলো অধিবক্তাক লগ কৰক",
    "home.testimonials.badge": "ক্লায়েন্টৰ মতামত",
    "home.testimonials.title": "নেতাসকলৰ বিশ্বাস",
    "contact.badge": "আমাৰ আইনী সেৱা",
    "contact.title": "গুৰুত্বপূৰ্ণ বিশেষজ্ঞতা",
    "contact.office": "শাখা কাৰ্যালয় আৰু হেল্পলাইন",
    "contact.officeDesc": "সকলো সোধা-পোছা কাৰ্য্যবাহী অধিবক্তা নীতিৰ অধীনত কঠোৰভাৱে গোপনীয় ৰখা হয়। আমাৰ কাৰ্যালয়লৈ আহক বা জৰুৰীকালীন ডেক্সৰ সৈতে যোগাযোগ কৰক।",
    "contact.branchChennai": "মুখ্য কাৰ্যালয় (চেন্নাই কাৰ্যালয়)",
    "contact.branchKarur": "শাখা কাৰ্যালয় (কাৰুৰ কাৰ্যালয়)",
    "contact.helpline": "জৰুৰীকালীন আইনী হেল্পলাইন",
    "contact.helplineDesc": "জামিন আৰু জৰুৰীকালীন আৰক্ষী জিম্মাৰ গোচৰৰ বাবে পোনপটীয়া যোগাযোগ (২৪/৭)",
    "contact.email": "ইমেইল সোধা-পোছা",
    "contact.hours": "কাৰ্যালয়ৰ সময়",
    "contact.hoursWeek": "সোমবাৰ - শুকুৰবাৰ: ৰাতিপুৱা ৯:০০ - সন্ধিয়া ৭:০০",
    "contact.hoursSat": "শনিবাৰ: ৰাতিপুৱা ১০:০০ - দুপৰীয়া ২:০০ (কেৱল নিযুক্তি)",
    "contact.formTitle": "গোপনীয় বাৰ্তা পঠিয়াওক",
    "contact.name": "পূৰ্ণ নাম",
    "contact.emailAddr": "ইমেইল ঠিকনা",
    "contact.phone": "ফোন নম্বৰ",
    "contact.message": "বাৰ্তা / গোচৰৰ তথ্য",
    "contact.btnSend": "বাৰ্তা পঠিয়াওক",
    "contact.successTitle": "সোধা-পোছা সফলভাৱে প্ৰেৰণ কৰা হৈছে",
    "contact.successDesc": "আপোনাৰ বাৰ্তা সুৰक्षितভাৱে প্ৰেৰণ কৰা হৈছে। আমাৰ এজন জ্যেষ্ঠ অংশীদাৰে ২৪ ঘণ্টাৰ ভিতৰত আপোনাৰ সৈতে যোগাযোগ কৰিব।",
    "contact.btnAnother": "আন একটা বাৰ্তা পঠিয়াওক",
    "footer.desc": "আৰাথাই (এ কে এম এছ'চিয়েটচ) কৰ্পোৰেট, প্ৰতিষ্ঠান আৰু ব্যক্তিসকলক প্ৰতিনিধিত্ব কৰা এক আগশাৰীৰ আইনী পৰামৰ্শ আৰু ওকালতি ফাৰ্ম।",
    "footer.contact": "যোগাযোগৰ তথ্য",
    "footer.rights": "সৰ্বস্বত্ব সংৰক্ষিত।",
    "footer.disclaimerTitle": "অধিবক্তা বিজ্ঞাপন অস্বীকাৰ পত্ৰ:",
    "footer.disclaimerText": "কিছুমান ন্যায়িক ক্ষেত্ৰত পেচাদাৰী আচৰণ বিধিৰ অধীনত, এই ছাইটৰ সমলসমূহ অধিবক্তা বিজ্ঞাপন বুলি গণ্য কৰিব পাৰি। পেছৰ ফলাফলসমূহে ভৱিষ্যতৰ একেধৰণৰ ফলাফলৰ গেৰাণ্টী নিদিয়ে। পৰামৰ্শ বুকিং কৰিলে কোনো আইনী সম্পৰ্ক গঢ়ি নুঠে।",
    "footer.privacy": "গোপনীয়তা নীতি",
    "footer.terms": "সেৱাৰ চৰ্তাৱলী",
    "footer.disclaimer": "অস্বীকাৰ পত্ৰ",
  },
  bn: {
    "nav.home": "মূল পাতা",
    "nav.practiceAreas": "আইনী ক্ষেত্রসমূহ",
    "nav.associates": "সহযোগীগণ",
    "nav.caseResults": "মামলার ফলাফল",
    "nav.insights": "নিবন্ধ ও ব্লগ",
    "nav.aboutUs": "আমাদের সম্পর্কে",
    "nav.contactUs": "যোগাযোগ করুন",
    "nav.bookConsultation": "পরামর্শ বুক করুন",
    "nav.allPractice": "সব আইনী ক্ষেত্র",
    "nav.attorneys": "আইনজীবীগণ",
    "hero.badge": "প্রিমিয়ার আইনী পরামর্শ ও ওকালতি",
    "hero.title1": "কর্তৃত্ব। সততা।",
    "hero.title2": "আপসহীন ফলাফল।",
    "hero.desc": "আরাথাই (এ কে এম অ্যাসোসিয়েটস) জটিল আইনী এক্তিয়ারের মাধ্যমে কর্পোরেশন, স্টার্টআপ এবং পরিবারগুলির प्रतिनिधित्व করে। আমরা আদালতে জয় এবং ব্যাপক আইনী সমাধান প্রদান করি।",
    "hero.btnIntake": "পরামর্শের সময়সূচী নির্ধারণ করুন",
    "hero.btnExplore": "আইনী ক্ষেত্রসমূহ দেখুন",
    "stats.exp.val": "১১+",
    "stats.exp.lbl": "বছরের সক্রিয় অভিজ্ঞতা",
    "stats.settle.val": "৯৮%",
    "stats.settle.lbl": "অনুকূল সমাধান",
    "stats.clients.val": "৫,০০০+",
    "stats.clients.lbl": "কর্পোরেট ও ব্যক্তিগত ক্লায়েন্ট",
    "stats.credentials.val": "উচ্চ শ্রেণী",
    "stats.credentials.lbl": "আইনী বার শংসাপত্র",
    "home.practice.badge": "বিশেষ আইনী ক্ষেত্র",
    "home.practice.title": "আইনী ক্ষেত্রসমূহ",
    "home.practice.desc": "আমাদের ফার্ম কর্পোরেট গভর্ন্যান্স, ভূমি স্বত্ব অডিট এবং আদালতে ওকালতিকে উচ্চ মানে পরিচালনা করে।",
    "home.practice.all": "সব আইনী ক্ষেত্র দেখুন",
    "home.team.badge": "অভিজ্ঞ আইনজীবী",
    "home.team.title": "প্রধান অংশীদারগণ",
    "home.team.desc": "বিশেষ জ্ঞান এবং দশকের আদালতের অভিজ্ঞতা সম্পন্ন উৎসর্গীকৃত আইনজীবীগণ।",
    "home.team.viewProfile": "প্রোফাইল দেখুন",
    "home.team.all": "সব আইনজীবীদের সাথে দেখা করুন",
    "home.testimonials.badge": "ক্লায়েন্টদের মতামত",
    "home.testimonials.title": "নেতাদের বিশ্বাস",
    "contact.badge": "আমাদের আইনী সেবা",
    "contact.title": "গুরুত্বপূর্ণ দক্ষতা",
    "contact.office": "শাखा কার্যালয় ও হেল্পলাইন",
    "contact.officeDesc": "সকল জিজ্ঞাসা আইনী নীতিমালার অধীনে কঠোরভাবে গোপনীয় রাখা হয়। আমাদের অফিসে আসুন বা জরুরি হেল্পলাইনে যোগাযোগ করুন।",
    "contact.branchChennai": "প্রধান কার্যালয় (চেন্নাই অফিস)",
    "contact.branchKarur": "শাখা কার্যালয় (কারুর অফিস)",
    "contact.helpline": "জরুরি আইনী হেল্পলাইন",
    "contact.helplineDesc": "জামিন ও জরুরি পুলিশ হেফাজতের মামলার জন্য সরাসরি যোগাযোগ (২৪/৭)",
    "contact.email": "ইমেল জিজ্ঞাসা",
    "contact.hours": "কার্যালয়ের সময়",
    "contact.hoursWeek": "সোমবার - শুক্রবার: সকাল ৯:০০ - সন্ধ্যা ৭:০০",
    "contact.hoursSat": "শনিবার: সকাল ১০:০০ - দুপুর ২:০০ (কেবল অ্যাপয়েন্টমেন্ট)",
    "contact.formTitle": "গোপনীয় বার্তা পাঠান",
    "contact.name": "পূর্ণ নাম",
    "contact.emailAddr": "ইমেল ঠিকানা",
    "contact.phone": "ফোন নম্বর",
    "contact.message": "বার্তা / মামলার বিবরণ",
    "contact.btnSend": "বার্তা পাঠান",
    "contact.successTitle": "জিজ্ঞাসা সফলভাবে পাঠানো হয়েছে",
    "contact.successDesc": "আপনার বার্তা সুরক্ষিতভাবে পাঠানো হয়েছে। আমাদের একজন সিনিয়র অংশীদার ২৪ ঘণ্টার মধ্যে আপনার সাথে যোগাযোগ করবেন।",
    "contact.btnAnother": "অন্য একটি বার্তা পাঠান",
    "footer.desc": "আরাথাই (এ কে এম অ্যাসোসিয়েটস) কর্পোরেট, প্রতিষ্ঠান এবং ব্যক্তিদের প্রতিনিধিত্বকারী একটি শীর্ষস্থানীয় আইনী পরামর্শ এবং ওকালতি ফার্ম।",
    "footer.contact": "যোগাযোগের তথ্য",
    "footer.rights": "সর্বস্বত্ব সংরক্ষিত।",
    "footer.disclaimerTitle": "আইনজীবী বিজ্ঞাপন দাবিত্যাগ:",
    "footer.disclaimerText": "কিছু বিচারব্যবস্থায় পেশাদার আচরণ বিধির অধীনে, এই সাইটের বিষয়বস্তু আইনজীবী বিজ্ঞাপন হিসাবে বিবেচিত হতে পারে। পূর্ববর্তী ফলাফল অনুরূপ ফলাফলের নিশ্চয়তা দেয় না। পরামর্শ বুকিং কোনো আইনী আইনজীবী-ক্লায়েন্ট সম্পর্ক তৈরি করে না।",
    "footer.privacy": "গোপনীয়তা নীতি",
    "footer.terms": "পরিষেবার শর্তাবলী",
    "footer.disclaimer": "দাবিত্যাগ",
  },
  gu: {
    "nav.home": "મુખ્ય પૃષ્ઠ",
    "nav.practiceAreas": "કાયદાકીય ક્ષેત્રો",
    "nav.associates": "સહયોગીઓ",
    "nav.caseResults": "કેસના પરિણામો",
    "nav.insights": "લેખો અને બ્લોગ",
    "nav.aboutUs": "અમારા વિશે",
    "nav.contactUs": "સંપર્ક કરો",
    "nav.bookConsultation": "પરામર્શ બુક કરો",
    "nav.allPractice": "તમામ કાયદાકીય ક્ષેત્રો",
    "nav.attorneys": "વકીલો",
    "hero.badge": "પ્રીમિયર કાયદાકીય પરામર્શ અને વકીલાત",
    "hero.title1": "સત્તા. પ્રામાણિકતા.",
    "hero.title2": "અનબિનસાંપ્રદાયિક પરિણામો.",
    "hero.desc": "આરાથાઈ (એકેએમ એસોસિએટ્સ) જટિલ કાયદાકીય ક્ષેત્રોમાં કોર્પોરેશનો, સ્ટાર્ટઅપ્સ અને પરિવારોનું પ્રતિનિધિત્વ કરે છે. અમે અદાલતોમાં વિજય અને વ્યાપક કાયદાકીય ઉકેલો પ્રદાન કરીએ છીએ.",
    "hero.btnIntake": "પરામર્શનો સમય નક્કી કરો",
    "hero.btnExplore": "કાયદાકીય ક્ષેત્રો જુઓ",
    "stats.exp.val": "11+",
    "stats.exp.lbl": "વર્ષોનો સક્રિય અનુભવ",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "સાનુકૂળ ઉકેલો",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "કોર્પોરેટ અને ખાનગી ગ્રાહકો",
    "stats.credentials.val": "ઉચ્ચ શ્રેણી",
    "stats.credentials.lbl": "લીગલ બાર ઓળખપત્ર",
    "home.practice.badge": "વિશિષ્ટ કાયદાકીય ક્ષેત્રો",
    "home.practice.title": "કાયદાકીય ક્ષેત્રો",
    "home.practice.desc": "અમારી પેઢી કોર્પોરેટ ગવર્નન્સ, જમીન માલિકી ઓડિટ અને કોર્ટમાં વકીલાતને ઉચ્ચ ધોરણે સંતુલિત કરે છે.",
    "home.practice.all": "તમામ કાયદાકીય ક્ષેત્રો જુઓ",
    "home.team.badge": "અનુભવી વકીલો",
    "home.team.title": "મુખ્ય ભાગીદારો",
    "home.team.desc": "વિશિષ્ટ જ્ઞાન અને દાયકાઓનો કોર્ટનો અનુભવ ધરાવતા સમર્પિત વકીલો.",
    "home.team.viewProfile": "પ્રોફાઇલ જુઓ",
    "home.team.all": "તમામ વકીલોને મળો",
    "home.testimonials.badge": "ગ્રાહકોનો પ્રતિસાદ",
    "home.testimonials.title": "નેતાઓનો વિશ્વાસ",
    "contact.badge": "અમારી કાયદાકીય સેવાઓ",
    "contact.title": "મહત્વપૂર્ણ કુશળતા",
    "contact.office": "શાખા કચેરીઓ અને હેલ્પલાઇન",
    "contact.officeDesc": "તમામ પૂછપરછ વ્યાવસાયિક વકીલ નિયમો હેઠળ સખત રીતે ગુપ્ત રાખવામાં આવે છે. અમારી ઑફિસની મુલાકાત લો અથવા હેલ્પલાઇનનો સંપર્ક કરો.",
    "contact.branchChennai": "મુખ્ય મથક (ચેન્નાઈ ઓફિસ)",
    "contact.branchKarur": "શાખા ઓફિસ (કરુર ઓફિસ)",
    "contact.helpline": "ઇમરજન્સી લીગલ હેલ્પલાઇન",
    "contact.helplineDesc": "જામીન અને તાત્કાલિક પોલીસ કસ્ટડીના કેસો માટે સીધો સંપર્ક (24/7)",
    "contact.email": "ઈમેઈલ પૂછપરછ",
    "contact.hours": "ઓફિસનો સમય",
    "contact.hoursWeek": "સોમવાર - શુક્રવાર: સવારે 9:00 - સાંજે 7:00",
    "contact.hoursSat": "શનિવાર: સવારે 10:00 - બપોરે 2:00 (ફક્ત એપોઇન્ટમેન્ટ)",
    "contact.formTitle": "ગુપ્ત પૂછપરછ મોકલો",
    "contact.name": "પૂરું નામ",
    "contact.emailAddr": "ઈમેલ સરનામું",
    "contact.phone": "ફોન નંબર",
    "contact.message": "સંદેશ / કેસની વિગતો",
    "contact.btnSend": "સંદેશ મોકલો",
    "contact.successTitle": "પૂછપરછ સફળતાપૂર્વક મોકલવામાં આવી",
    "contact.successDesc": "તમારો સંદેશ સુરક્ષિત રીતે મોકલી દેવામાં આવ્યો છે. અમારા વરિષ્ઠ ભાગીદાર 24 કલાકમાં તમારો સંપર્ક કરશે.",
    "contact.btnAnother": "બીજો સંદેશ મોકલો",
    "footer.desc": "આરાથાઈ (એકેએમ એસોસિએટ્સ) કોર્પોરેટ્સ, સંસ્થાઓ અને વ્યક્તિઓનું પ્રતિનિધિત્વ કરતી એક અગ્રણી કાયદાકીય પરામર્શ અને વકીલાત પેઢી છે.",
    "footer.contact": "સંપર્ક માહિતી",
    "footer.rights": "તમામ હકો અનામત.",
    "footer.disclaimerTitle": "વકીલ જાહેરાત અસ્વીકરણ:",
    "footer.disclaimerText": "કેટલાક અધિકારક્ષેત્રોમાં વ્યાવસાયિક આચરણના નિયમો હેઠળ, આ સાઇટની સામગ્રીને વકીલની જાહેરાત ગણી શકાય. અગાઉના પરિણામો ભવિષ્યના સમાન પરિણામોની બાંયધરી આપતા નથી. પરામર્શ બુકિંગથી વકીલ-ગ્રાહક સંબંધ બનતો નથી.",
    "footer.privacy": "ગોપનીયતા નીતિ",
    "footer.terms": "સેવાની શરતો",
    "footer.disclaimer": "અસ્વીકરણ",
  },
  kn: {
    "nav.home": "ಮುಖ್ಯ ಪುಟ",
    "nav.practiceAreas": "ಕಾನೂನು ಕ್ಷೇತ್ರಗಳು",
    "nav.associates": "ಸಹವರ್ತಿಗಳು",
    "nav.caseResults": "ಪ್ರಕರಣದ ಫಲಿತಾಂಶಗಳು",
    "nav.insights": "ಲೇಖನಗಳು ಮತ್ತು ಬ್ಲಾಗ್",
    "nav.aboutUs": "ನಮ್ಮ ಬಗ್ಗೆ",
    "nav.contactUs": "ಸಂಪರ್ಕಿಸಿ",
    "nav.bookConsultation": "ಸಮಾಲೋಚನೆ ಬುಕ್ ಮಾಡಿ",
    "nav.allPractice": "ಎಲ್ಲಾ ಕಾನೂನು ಕ್ಷೇತ್ರಗಳು",
    "nav.attorneys": "ವಕೀಲರು",
    "hero.badge": "ಪ್ರಮುಖ ಕಾನೂನು ಸಮಾಲೋಚನೆ ಮತ್ತು वकालंत्ता",
    "hero.title1": "ಅಧಿಕಾರ. ಪ್ರಾಮಾಣಿಕತೆ.",
    "hero.title2": "ರಾಜಿ ಇಲ್ಲದ ಫಲಿತಾಂಶಗಳು.",
    "hero.desc": "ಆರಾಥಾಯಿ (ಎಕೆಎಂ ಅಸೋಸಿಯೇಟ್ಸ್) ಸಂಕೀರ್ಣ ಕಾನೂನು ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ಕಾರ್ಪೊರೇಷನ್‌ಗಳು, ಸ್ಟಾರ್ಟ್‌ಅಪ್‌ಗಳು ಮತ್ತು ಕುಟುಂಬಗಳನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ. ನಾವು ನ್ಯಾಯಾಲಯಗಳಲ್ಲಿ ವಿಜಯ ಮತ್ತು ಸಮಗ್ರ ಕಾನೂನು ಪರಿಹಾರಗಳನ್ನು ನೀಡುತ್ತೇವೆ.",
    "hero.btnIntake": "ಸಮಾಲೋಚನೆಯ ಸಮಯ ನಿಗದಿಪಡಿಸಿ",
    "hero.btnExplore": "ಕಾನೂನು ಕ್ಷೇತ್ರಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    "stats.exp.val": "11+",
    "stats.exp.lbl": "ವರ್ಷಗಳ ಸಕ್ರಿಯ ಅನುಭವ",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "ಅನುಕೂಲಕರ ಪರಿಹಾರಗಳು",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "ಕಾರ್ಪೊರೇಟ್ ಮತ್ತು ಖಾಸಗಿ ಗ್ರಾಹಕರು",
    "stats.credentials.val": "ಉನ್ನತ ದರ್ಜೆ",
    "stats.credentials.lbl": "ಲೀಗಲ್ ಬಾರ್ ರುಜುವಾತುಗಳು",
    "home.practice.badge": "ವಿಶೇಷ ಕಾನೂನು ಕ್ಷೇತ್ರಗಳು",
    "home.practice.title": "ಕಾನೂನು ಕ್ಷೇತ್ರಗಳು",
    "home.practice.desc": "ನಮ್ಮ ಸಂಸ್ಥೆಯು ಕಾರ್ಪೊರೇಟ್ ಆಡಳಿತ, ಭೂ ಮಾಲೀಕತ್ವದ ಆಡಿಟ್ ಮತ್ತು ಕೋರ್ಟ್ ವಕಾಲತ್ತನ್ನು ಉನ್ನತ ಗುಣಮಟ್ಟದಲ್ಲಿ ನಿರ್ವಹಿಸುತ್ತದೆ.",
    "home.practice.all": "ಎಲ್ಲಾ ಕಾನೂನು ಕ್ಷೇತ್ರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    "home.team.badge": "ಅನುಭವಿ ವಕೀಲರು",
    "home.team.title": "ಮುಖ್ಯ ಪಾಲುದಾರರು",
    "home.team.desc": "ವಿಶೇಷ ಜ್ಞಾನ ಮತ್ತು ದಶಕಗಳ ಕೋರ್ಟ್ ಅನುಭವ ಹೊಂದಿರುವ ಸಮರ್ಪಿತ ವಕೀಲರು.",
    "home.team.viewProfile": "ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ",
    "home.team.all": "ಎಲ್ಲಾ ವಕೀಲರನ್ನು ಭೇಟಿ ಮಾಡಿ",
    "home.testimonials.badge": "ಗ್ರಾಹಕರ ಪ್ರತಿಕ್ರಿಯೆ",
    "home.testimonials.title": "ನಾಯಕರ ವಿಶ್ವಾಸ",
    "contact.badge": "ನಮ್ಮ ಕಾನೂನು ಸೇವೆಗಳು",
    "contact.title": "ಪ್ರಮುಖ ಪರಿಣತಿ",
    "contact.office": "ಶಾಖಾ ಕಚೇರಿಗಳು ಮತ್ತು ಸಹಾಯವಾಣಿ",
    "contact.officeDesc": "ಎಲ್ಲಾ ವಿಚಾರಣೆಗಳನ್ನು ವೃತ್ತಿපರ ವಕೀಲರ ನಿಯಮಗಳ ಅಡಿಯಲ್ಲಿ ಕಟ್ಟುನಿಟ್ಟಾಗಿ ರಹಸ್ಯವಾಗಿಡಲಾಗುತ್ತದೆ. ನಮ್ಮ ಕಚೇರಿಗೆ ಭೇಟಿ ನೀಡಿ ಅಥವಾ ಸಹಾಯವಾಣಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "contact.branchChennai": "ಮುಖ್ಯ ಕಚೇರಿ (ಚೆನ್ನೈ ಕಚೇರಿ)",
    "contact.branchKarur": "ಶಾಖಾ ಕಚೇರಿ (ಕರೂರ್ ಕಚೇರಿ)",
    "contact.helpline": "ತುರ್ತು ಕಾನೂನು ಸಹಾಯವಾಣಿ",
    "contact.helplineDesc": "ಜಾಮೀನು ಮತ್ತು ತಕ್ಷಣದ ಪೊಲೀಸ್ ಕస్టಡಿ ಪ್ರಕರಣಗಳಿಗಾಗಿ ನೇರ ಸಂಪర్క (24/7)",
    "contact.email": "ಇಮೇಲ್ ವಿಚಾರಣೆಗಳು",
    "contact.hours": "ಕಚೇರಿ ಸಮಯ",
    "contact.hoursWeek": "ಸೋಮವಾರ - ಶುಕ್ರವಾರ: ಬೆಳಿಗ್ಗೆ 9:00 - ಸಂಜೆ 7:00",
    "contact.hoursSat": "শనిવાર: ಬೆಳಿಗ್ಗೆ 10:00 - ಮಧ್ಯಾಹ್ನ 2:00 (ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಮಾತ್ರ)",
    "contact.formTitle": "ರಹಸ್ಯ ವಿಚಾರಣೆ ಕಳುಹಿಸಿ",
    "contact.name": "ಪೂರ್ಣ ಹೆಸರು",
    "contact.emailAddr": "ಇಮೇಲ್ ವಿಳಾಸ",
    "contact.phone": "ಫೋನ್ ಸಂಖ್ಯೆ",
    "contact.message": "ಸಂದೇಶ / ಪ್ರಕರಣದ ವಿವರಗಳು",
    "contact.btnSend": "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    "contact.successTitle": "ವಿಚಾರಣೆ ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ",
    "contact.successDesc": "ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ. ನಮ್ಮ ಹಿರಿಯ ಪಾಲುದಾರರು 24 ಗಂಟೆಗಳ ಒಳಗೆ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ.",
    "contact.btnAnother": "ಮತ್ತೊಂದು ಸಂದೇಶ ಕಳುಹಿಸಿ",
    "footer.desc": "ಆರಾಥಾಯಿ (ಎಕೆಎಂ ಅಸೋಸಿಯೇಟ್ಸ್) ಕಾರ್ಪೊರೇಟ್‌ಗಳು, ಸಂಸ್ಥೆಗಳು ಮತ್ತು ವ್ಯಕ್ತಿಗಳನ್ನು ಪ್ರತಿನಿಧಿಸುವ ಒಂದು ಪ್ರಮುಖ ಕಾನೂನು ಸಮಾಲೋಚನೆ आणि ವಕಾಲತ್ತು ಸಂಸ್ಥೆಯಾಗಿದೆ.",
    "footer.contact": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    "footer.rights": "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    "footer.disclaimerTitle": "ವಕೀಲರ ಜಾಹೀರಾತು ಹಕ್ಕುತ್ಯಾಗ:",
    "footer.disclaimerText": "ಕೆಲವು ನ್ಯಾಯವ್ಯಾಪ್ತಿಗಳಲ್ಲಿ ವೃತ್ತಿಪರ ನಡತೆಯ ನಿಯಮಗಳ ಅಡಿಯಲ್ಲಿ, ಈ ಸೈಟ್‌ನ ವಿಷಯಗಳನ್ನು ವಕೀಲರ ಜಾಹೀರಾತು ಎಂದು ಪರಿಗಣಿಸಬಹುದು. ಹಿಂದಿನ ಫಲಿತಾಂಶಗಳು ಭವಿಷ್ಯದ ಇದೇ ರೀತಿಯ ಫಲಿತಾಂಶಗಳನ್ನು ಖಾತರಿಪಡಿಸುವುದಿಲ್ಲ. ಸಮಾಲೋಚನೆ ಬುಕಿಂಗ್‌ನಿಂದ ವಕೀಲ-ಗ್ರಾಹಕ ಸಂಬಂಧ ಉಂಟಾಗುವುದಿಲ್ಲ.",
    "footer.privacy": "ಗೌಪ್ಯತಾ ನೀತಿ",
    "footer.terms": "ಸೇವಾ ನಿಯಮಗಳು",
    "footer.disclaimer": "ಹಕ್ಕುತ್ಯಾಗ",
  },
  ml: {
    "nav.home": "ഹോം",
    "nav.practiceAreas": "നിയമ മേഖലകൾ",
    "nav.associates": "സഹപ്രവർത്തകർ",
    "nav.caseResults": "കേസ് ഫലങ്ങൾ",
    "nav.insights": "ലേഖനങ്ങളും ബ്ലോഗും",
    "nav.aboutUs": "ഞങ്ങളെക്കുറിച്ച്",
    "nav.contactUs": "ബന്ധപ്പെടുക",
    "nav.bookConsultation": "കൺസൾട്ടേഷൻ ബുക്ക് ചെയ്യുക",
    "nav.allPractice": "എല്ലാ നിയമ മേഖലകളും",
    "nav.attorneys": "അഭിഭാഷകർ",
    "hero.badge": "പ്രമുഖ നിയമ കൺസൾട്ടൻസിയും അഡ്വക്കസിയും",
    "hero.title1": "അധികാരം. സമഗ്രത.",
    "hero.title2": "വിട്ടുവീഴ്ചയില്ലാത്ത ഫലങ്ങൾ.",
    "hero.desc": "അരത്തായി (എകെഎം അസോസിയേറ്റ്സ്) സങ്കീർണ്ണമായ അധികാരപരിധികളിലൂടെ കോർപ്പറേഷനുകൾ, സ്റ്റാർട്ടപ്പുകൾ, കുടുംബങ്ങൾ എന്നിവയെ പ്രതിനിധീകരിക്കുന്നു. ഞങ്ങൾ കോടതികളിൽ വിജയവും സമഗ്രമായ നിയമ പരിഹാരങ്ങളും നൽകുന്നു.",
    "hero.btnIntake": "കൺസൾട്ടേഷൻ സമയം നിശ്ചയിക്കുക",
    "hero.btnExplore": "നിയമ മേഖലകൾ പരിശോധിക്കുക",
    "stats.exp.val": "11+",
    "stats.exp.lbl": "വർഷത്തെ സജീവ പരിചയം",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "അനുകൂലമായ പരിഹാരങ്ങൾ",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "കോർപ്പറേറ്റ്, സ്വകാര്യ ക്ലയന്റുകൾ",
    "stats.credentials.val": "ഉന്നത നിലവാരം",
    "stats.credentials.lbl": "ലീഗൽ ബാർ യോഗ്യതാപത്രങ്ങൾ",
    "home.practice.badge": "പ്രത്യേക നിയമ മേഖലകൾ",
    "home.practice.title": "നിയമ മേഖലകൾ",
    "home.practice.desc": "ഞങ്ങളുടെ സ്ഥാപനം കോർപ്പറേറ്റ് ഗവേണൻസ്, ഭൂമി ഉടമസ്ഥാവകാശ ഓഡിറ്റ്, കോടതി അഡ്വക്കസി എന്നിവ ഉന്നത നിലവാരത്തിൽ നിർവ്വഹിക്കുന്നു.",
    "home.practice.all": "എല്ലാ നിയമ മേഖലകളും കാണുക",
    "home.team.badge": "പരിചയസമ്പന്നരായ അഭിഭാഷകർ",
    "home.team.title": "പ്രധാന പങ്കാളികൾ",
    "home.team.desc": "പ്രത്യേക അറിവും പതിറ്റാണ്ടുകളുടെ കോടതി പരിചയവുമുള്ള സമർപ്പിതരായ അഭിഭാഷകർ.",
    "home.team.viewProfile": "പ്രൊഫൈൽ കാണുക",
    "home.team.all": "എല്ലാ അഭിഭാഷകരെയും കാണുക",
    "home.testimonials.badge": "ക്ലയന്റുകളുടെ പ്രതികരണം",
    "home.testimonials.title": "നേതാക്കളുടെ വിശ്വാസം",
    "contact.badge": "ഞങ്ങളുടെ നിയമ സേവനങ്ങൾ",
    "contact.title": "പ്രധാനപ്പെട്ട വൈദഗ്ധ്യം",
    "contact.office": "ബ്രാഞ്ച് ഓഫീസുകളും ഹെൽപ്പ് ലൈനും",
    "contact.officeDesc": "എല്ലാ അന്വേഷണങ്ങളും പ്രൊഫഷണൽ അഭിഭാഷക ചട്ടങ്ങൾക്ക് കീഴിൽ കർശനമായി രഹസ്യമായി സൂക്ഷിക്കുന്നു. ഞങ്ങളുടെ ഓഫീസ് സന്ദർശിക്കുക അല്ലെങ്കിൽ ഹെൽപ്പ് ലൈനിൽ ബന്ധപ്പെടുക.",
    "contact.branchChennai": "ആസ്ഥാനം (ചെന്നൈ ഓഫീസ്)",
    "contact.branchKarur": "ബ്രാഞ്ച് ഓഫീസ് (കരൂർ ഓഫീസ്)",
    "contact.helpline": "അടിയന്തര നിയമ ഹെൽപ്പ് ലൈൻ",
    "contact.helplineDesc": "ജാമ്യം, അടിയന്തര പോലീസ് കസ്റ്റഡി കേസുകൾ എന്നിവയ്ക്കുള്ള നേരിട്ടുള്ള ബന്ധം (24/7)",
    "contact.email": "ഇമെയിൽ അന്വേഷണങ്ങൾ",
    "contact.hours": "ഓഫീസ് സമയം",
    "contact.hoursWeek": "തിങ്കൾ - വെള്ളി: രാവിലെ 9:00 - വൈകുന്നേരം 7:00",
    "contact.hoursSat": "ശനി: രാവിലെ 10:00 - ഉച്ചയ്ക്ക് 2:00 (അപ്പോയിന്റ്മെന്റ് മാത്രം)",
    "contact.formTitle": "രഹസ്യ അന്വേഷണം അയക്കുക",
    "contact.name": "പൂർണ്ണമായ പേര്",
    "contact.emailAddr": "ഇമെയിൽ वിലാസം",
    "contact.phone": "ഫോൺ നമ്പർ",
    "contact.message": "സന്ദേശം / കേസ് വിവരങ്ങൾ",
    "contact.btnSend": "സന്ദേശം അയക്കുക",
    "contact.successTitle": "അന്വേഷണം വിജയകരമായി അയച്ചു",
    "contact.successDesc": "നിങ്ങളുടെ സന്ദേശം സുരക്ഷിതമായി അയച്ചു കഴിഞ്ഞു. ഞങ്ങളുടെ ഒരു സീനിയർ പങ്കാളി 24 മണിക്കൂറിനുള്ളിൽ നിങ്ങളെ ബന്ധപ്പെടും.",
    "contact.btnAnother": "മറ്റൊരു സന്ദേശം അയക്കുക",
    "footer.desc": "കോർപ്പറേറ്റുകൾ, സ്ഥാപനങ്ങൾ, വ്യക്തികൾ എന്നിവരെ പ്രതിനിധീകരിക്കുന്ന പ്രമുഖ നിയമ കൺസൾട്ടൻസിയും അഡ്വക്കസി സ്ഥാപനവുമാണ് അരത്തായി (എകെഎം അസോസിയേറ്റ്സ്).",
    "footer.contact": "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
    "footer.rights": "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
    "footer.disclaimerTitle": "അഭിഭാഷക പരസ്യ നിരാകരണം:",
    "footer.disclaimerText": "ചില അധികാരപരിധികളിലെ പ്രൊഫഷണൽ പെരുമാറ്റച്ചട്ടങ്ങൾ അനുസരിച്ച്, ഈ സൈറ്റിലെ ഉള്ളടക്കങ്ങൾ അഭിഭാഷക പരസ്യമായി കണക്കാക്കാം. മുൻകാല ഫലങ്ങൾ ഭാവിയിൽ സമാനമായ ഫലങ്ങൾ ഉറപ്പ് നൽകുന്നില്ല. കൺസൾട്ടേഷൻ ബുക്കിംഗുകൾ അഭിഭാഷക-ക്ലയന്റ് ബന്ധത്തിന് കാരണമാകില്ല.",
    "footer.privacy": "സ്വകാര്യതാ നയം",
    "footer.terms": "സേവന വ്യവസ്ഥകൾ",
    "footer.disclaimer": "നിരാകരണം",
  },
  mr: {
    "nav.home": "मुख्य पृष्ठ",
    "nav.practiceAreas": "कायदेविषयक क्षेत्रे",
    "nav.associates": "सहयोगी वकील",
    "nav.caseResults": "खटल्यांचे निकाल",
    "nav.insights": "लेख आणि ब्लॉग",
    "nav.aboutUs": "आमच्याबद्दल",
    "nav.contactUs": "संपर्क करा",
    "nav.bookConsultation": "सल्लामसलत बुक करा",
    "nav.allPractice": "सर्व कायदेविषयक क्षेत्रे",
    "nav.attorneys": "वकील",
    "hero.badge": "प्रमुख कायदेविषयक सल्ला आणि वकिली",
    "hero.title1": "अधिकार. सत्यनिष्ठा.",
    "hero.title2": "तडजोडविरहित निकाल.",
    "hero.desc": "आरथाई (एकेएम असोसिएट्स) कॉर्पोरेशन, स्टार्टअप्स आणि कुटुंबांचे जटिल कायदेशीर क्षेत्रांमध्ये प्रतिनिधित्व करते. आम्ही न्यायालयांमध्ये विजय आणि व्यापक कायदेशीर उपाय प्रदान करतो.",
    "hero.btnIntake": "गोपनीय सल्लामसलत बुक करा",
    "hero.btnExplore": "कार्यक्षेत्रे पहा",
    "stats.exp.val": "११+",
    "stats.exp.lbl": "वर्षांचा सक्रिय अनुभव",
    "stats.settle.val": "९८%",
    "stats.settle.lbl": "सकारात्मक निकाल",
    "stats.clients.val": "५,०००+",
    "stats.clients.lbl": "कॉर्पोरेट आणि खाजगी क्लायंट",
    "stats.credentials.val": "सर्वोच्च श्रेणी",
    "stats.credentials.lbl": "बार असोसिएशन प्रमाणपत्रे",
    "home.practice.badge": "विशेष कायदेशीर क्षेत्रे",
    "home.practice.title": "कायदेशीर कार्यक्षेत्रे",
    "home.practice.desc": "आमची फर्म कॉर्पोरेट प्रशासन, जमीन मालकी ऑडिट आणि न्यायालयात वकिली उच्च मानकांवर संतुलित करते.",
    "home.practice.all": "सर्व कार्यक्षेत्रे पहा",
    "home.team.badge": "अनुभवी वकील",
    "home.team.title": "मुख्य भागीदार",
    "home.team.desc": "विशेष ज्ञान आणि दशकांचा न्यायालयीन अनुभव असलेले समर्पित वकील.",
    "home.team.viewProfile": "प्रोफाइल पहा",
    "home.team.all": "सर्व वकीलांना भेटा",
    "home.testimonials.badge": "क्लायंट अभिप्राय",
    "home.testimonials.title": "नेत्यांचा विश्वास",
    "contact.badge": "आमच्या कायदेशीर सेवा",
    "contact.title": "महत्त्वपूर्ण कौशल्य",
    "contact.office": "शाखा कार्यालये आणि हेल्पलाइन",
    "contact.officeDesc": "व्यावसायिक वकील नियमांतर्गत सर्व चौकशी पूर्णपणे गोपनीय ठेवली जाते. आमच्या कार्यालयांना भेट द्या किंवा हेल्पलाइनशी संपर्क साधा.",
    "contact.branchChennai": "मुख्यालय (चेन्नई कार्यालय)",
    "contact.branchKarur": "शाखा कार्यालय (करूर कार्यालय)",
    "contact.helpline": "अतितातडीची कायदेशीर हेल्पलाइन",
    "contact.helplineDesc": "जामीन आणि त्वरित पोलीस कोठडीच्या प्रकरणांसाठी थेट संपर्क (२४/७)",
    "contact.email": "ईमेल चौकशी",
    "contact.hours": "कार्यालयीन वेळ",
    "contact.hoursWeek": "सोमवार - शुक्रवार: सकाळी ९:०० - संध्याकाळी ७:००",
    "contact.hoursSat": "शनिवार: सकाळी १०:०० - दुपारी २:०० (फक्त भेटीसाठी)",
    "contact.formTitle": "गोपनीय चौकशी पाठवा",
    "contact.name": "पूर्ण नाव",
    "contact.emailAddr": "ईमेल पत्ता",
    "contact.phone": "फोन नंबर",
    "contact.message": "संदेश / प्रकरणाचा तपशील",
    "contact.btnSend": "संदेश पाठवा",
    "contact.successTitle": "चौकशी यशस्वीरित्या पाठवली",
    "contact.successDesc": "तुमचा संदेश सुरक्षितपणे पाठवला गेला आहे. आमचे एक वरिष्ठ भागीदार २४ तासांच्या आत तुमच्याशी संपर्क साधतील.",
    "contact.btnAnother": "दुसरा संदेश पाठवा",
    "footer.desc": "आरथाई (एकेएम असोसिएट्स) ही कॉर्पोरेट्स, संस्था आणि व्यक्तींचे प्रतिनिधित्व करणारी एक अग्रणी कायदेशीर सल्लागार आणि वकिली संस्था आहे.",
    "footer.contact": "संपर्क माहिती",
    "footer.rights": "सर्व हक्क राखीव.",
    "footer.disclaimerTitle": "वकील जाहिरात अस्वीकरण:",
    "footer.disclaimerText": "काही अधिकारक्षेत्रातील व्यावसायिक आचार नियमांनुसार, या साइटवरील सामग्री वकील जाहिरात मानली जाऊ शकते. मागील निकाल भविष्यातील निकालांची हमी देत नाहीत. सल्लामसलत बुकिंगमुळे वकील-क्लायंट संबंध निर्माण होत नाही.",
    "footer.privacy": "गोपनीयता धोरण",
    "footer.terms": "सेवेच्या अटी",
    "footer.disclaimer": "अस्वीकरण",
  },
  or: {
    "nav.home": "ମୁଖ୍ୟ ପୃଷ୍ଠା",
    "nav.practiceAreas": "ଆଇନଗତ କ୍ଷେତ୍ର",
    "nav.associates": "ସହଯୋଗୀ",
    "nav.caseResults": "ମାମଲା ଫଳାଫଳ",
    "nav.insights": "ପ୍ରବନ୍ଧ ଏବଂ ବ୍ଲଗ୍",
    "nav.aboutUs": "ଆମ ବିଷୟରେ",
    "nav.contactUs": "ସମ୍ପର୍କ କରନ୍ତୁ",
    "nav.bookConsultation": "ପରାମର୍ଶ ବୁକ୍ କରନ୍ତୁ",
    "nav.allPractice": "ସମସ୍ତ ଆଇନଗତ କ୍ଷେତ୍ର",
    "nav.attorneys": "ଓକିଲମାନେ",
    "hero.badge": "ପ୍ରମୁଖ ଆଇନଗତ ପରାମର୍ଶ ଏବଂ ଓକିଲାତି",
    "hero.title1": "କର୍ତ୍ତୃତ୍ୱ। ସତ୍ୟନିଷ୍ଠା।",
    "hero.title2": "ଆପୋଷହୀନ ଫଳାଫଳ।",
    "hero.desc": "ଆରାଥାଇ (ଏକେଏମ୍ ଆସୋସିଏଟ୍ସ) ଜଟିଳ ଆଇନଗତ କ୍ଷେତ୍ରରେ କର୍ପୋରେସନ୍, ଷ୍ଟାର୍ଟଅପ୍ ଏବଂ ପରିବାରଗୁଡିକର ପ୍ରତିନିଧିତ୍ୱ କରେ। ଆମେ କୋର୍ଟରେ ବିଜୟ ଏବଂ ବ୍ୟାପକ ଆଇନଗତ ସମାଧାନ ପ୍ରଦାନ କରୁ।",
    "hero.btnIntake": "ପରାମର୍ଶ ସମୟ ସ୍ଥିର କରନ୍ତು",
    "hero.btnExplore": "ଆଇନଗତ କ୍ଷେତ୍ରଗୁଡିକ ଦେଖନ୍ତୁ",
    "stats.exp.val": "୧୧+",
    "stats.exp.lbl": "ବର୍ଷର ସକ୍ରିୟ ଅଭିଜ୍ଞତା",
    "stats.settle.val": "୯୮%",
    "stats.settle.lbl": "ଅନୁକୂଳ ସମାଧାନ",
    "stats.clients.val": "୫,୦୦clock+",
    "stats.clients.lbl": "କର୍ପୋରେଟ୍ ଏବଂ ବ୍ୟକ୍ତିଗତ କ୍ଲାଏଣ୍ଟ",
    "stats.credentials.val": "ଉଚ୍ଚ ଶ୍ରେଣୀ",
    "stats.credentials.lbl": "ଆଇନଗତ ବାର୍ ପ୍ରମାଣପତ୍ର",
    "home.practice.badge": "ବିଶେଷ ଆଇନଗତ କ୍ଷେତ୍ର",
    "home.practice.title": "ଆଇନଗତ କ୍ଷେତ୍ର",
    "home.practice.desc": "ଆମ ଫାର୍ମ କର୍ପୋରେଟ୍ ଶାସନ, ଭୂମି ମାଲିକାନା ଅଡିଟ୍ ଏବଂ କୋର୍ଟ ଓକିଲାତିକୁ ଉଚ୍ଚ ମାନଦଣ୍ଡରେ ସନ୍ତୁଳିତ କରେ।",
    "home.practice.all": "ସମସ୍ତ ଆଇନଗତ କ୍ଷେତ୍ର ଦେଖନ୍ତୁ",
    "home.team.badge": "ଅଭିଜ୍ଞ ଓକିଲ",
    "home.team.title": "ମୁଖ୍ୟ ଭାଗିଦାର",
    "home.team.desc": "ବିଶେଷ ଜ୍ଞาน ଏବଂ ଦଶନ୍ଧିର କୋର୍ଟ ଅଭିଜ୍ଞତା ଥିବା ସମର୍ପିତ ଓକିଲମାନେ।",
    "home.team.viewProfile": "ପ୍ରୋଫାଇଲ୍ ଦେଖନ୍ତୁ",
    "home.team.all": "ସମସ୍ତ ଓକିଲଙ୍କୁ ଭେଟନ୍ତୁ",
    "home.testimonials.badge": "କ୍ଲାଏଣ୍ଟ ପ୍ରତିକ୍ରିୟା",
    "home.testimonials.title": "ନେତାମାନଙ୍କ ବିଶ୍ୱାସ",
    "contact.badge": "ଆମର ଆଇନଗତ ସେବା",
    "contact.title": "ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଦକ୍ଷତା",
    "contact.office": "ଶାଖା କାର୍ଯ୍ୟାଳୟ ଏବଂ ହେଲ୍ପଲାଇନ",
    "contact.officeDesc": "ସମସ୍ତ ପଚରାଉଚରା ବ୍ୟାବସାୟିକ ଓକିଲ ନିୟମ ଅନୁଯାୟୀ କଡାକଡି ଭାବେ ଗୋପନୀୟ ରଖାଯାଏ। ଆମ କାର୍ଯ୍ୟାଳୟ ପରିଦର୍ଶନ କରନ୍ତୁ କିମ୍ବା ହେଲ୍ପଲାଇନରେ ଯୋଗାଯୋਗ କରନ୍ତು।",
    "contact.branchChennai": "ମୁଖ୍ୟ କାର୍ଯ୍ୟାଳୟ (ଚେନ୍ନਾਈ କାର୍ଯ୍ୟାଳୟ)",
    "contact.branchKarur": "ଶାଖା କାର୍ଯ୍ୟାଳୟ (କରୁର କାର୍ଯ୍ୟାଳୟ)",
    "contact.helpline": "ଜରຸରୀକାଳୀନ ଆଇନଗତ ହେଲ୍ପଲାଇନ",
    "contact.helplineDesc": "ଜାମିନ ଏବଂ ତୁରନ୍ତ ପୋଲିସ ହେପାజତ ମାମଲା ପାଇଁ ସିଧାସଳଖ ଯୋਗାଯୋਗ (୨୪/୭)",
    "contact.email": "ଇମେଲ୍ ପଚରାଉଚରା",
    "contact.hours": "କାର୍ଯ୍ୟାଳୟ ସମୟ",
    "contact.hoursWeek": "ସୋମବାର - ଶୁକ୍ରବାର: ସକାଳ ୯:০০ - ସନ୍ଧ୍ୟା ୭:୦",
    "contact.hoursSat": "ଶନିବାର: ସକାଳ ୧୦:୦୦ - ଦିପହର ୨:୦୦ (କେବଳ ନିଯୁକ୍ତି)",
    "contact.formTitle": "ଗୋପନୀୟ ବାର୍ତ୍ତା ପଠାନ୍ତୁ",
    "contact.name": "ପୂରା ନାମ",
    "contact.emailAddr": "ଇମେଲ୍ ଠିକଣା",
    "contact.phone": "ଫୋନ୍ ନମ୍ବਰ",
    "contact.message": "বାର୍ତ୍ତା / ମାମଲା ବିବରଣୀ",
    "contact.btnSend": "বାର୍ତ୍ତା ପଠାନ୍ତୁ",
    "contact.successTitle": "ବାର୍ତ୍ତା ସଫଳତାର ସହ ପଠାଗଲା",
    "contact.successDesc": "ଆପଣଙ୍କ ବାର୍ତ୍ତା ସୁରକ୍ଷିତ ଭାବେ ପଠାଯାଇଛି। ଆମର ଜଣେ ବରିଷ୍ଠ ସହଯୋଗୀ ୨୪ ଘଣ୍ଟା ମଧ୍ୟରେ ଯୋਗାଯୋਗ କରିବେ।",
    "contact.btnAnother": "ଅନ୍ୟ ଏକ ବାର୍ତ୍ତା ପଠାନ୍ତୁ",
    "footer.desc": "ଆରାଥାଇ (ଏକେଏମ୍ ଆସୋସିଏଟ୍ସ) ହେଉଛି କର୍ପୋରେଟ୍, ଅନୁଷ୍ଠାନ ଏବଂ ବ୍ୟକ୍ତିବିଶେଷଙ୍କ ପ୍ରତିନિଧିତ୍ୱ କରୁଥିବା ଏକ ପ୍ରମୁଖ ଆଇନଗତ ପରାମର୍ଶ ଏବଂ ଓକିଲାତି ଫାର୍ମ।",
    "footer.contact": "ସମ୍ପର୍କ ସୂଚନା",
    "footer.rights": "ସର୍ବସତ୍ତ୍ୱ ସଂରକ୍ଷିତ।",
    "footer.disclaimerTitle": "ଓକિଲ ବିଜ୍ଞାପନ ଦାବିତ୍ୟାଗ:",
    "footer.disclaimerText": "କେତେକ ଆଇନଗତ କ୍ଷେତ୍ରରେ ବ୍ୟାବସାୟିକ ଆଚରଣ ନିୟମ ଅନୁଯାୟୀ, ଏହି ସାଇଟର ବିଷୟବସ୍ତୁ ଓକିଲ ବିଜ୍ଞାପନ ଭାବେ ବିବେଚନା କରାଯାଇପାରେ। ପୂର୍ବ ଫଳାଫଳ ଭବିଷ୍ୟତର ସମାନ ଫଳାଫଳର ଗ୍ୟାରେଣ୍ଟି ଦିଏ ନାହିଁ। ପରାମର୍ଶ ବୁକିଂ ଦ୍ୱାରା କୌଣସି ଆଇନଗତ ସମ୍ପର୍କ ସୃଷ୍ଟି ହୁଏ ନାହିଁ।",
    "footer.privacy": "ଗୋପନୀୟତା ନୀତି",
    "footer.terms": "ସେବା ସର୍ତ୍ତାବଳୀ",
    "footer.disclaimer": "ନାମଞ୍ਜୁਰୀ",
  },
  pa: {
    "nav.home": "ਮੁੱਢਲਾ ਪੰਨਾ",
    "nav.practiceAreas": "ਕਾਨੂੰਨੀ ਖੇਤਰ",
    "nav.associates": "ਸਹਿਯੋਗੀ",
    "nav.caseResults": "ਕੇਸਾਂ ਦੇ ਨਤੀਜੇ",
    "nav.insights": "ਲੇਖ ਅਤੇ ਬਲੌਗ",
    "nav.aboutUs": "ਸਾਡੇ ਬਾਰੇ",
    "nav.contactUs": "ਸੰਪਰਕ ਕਰੋ",
    "nav.bookConsultation": "ਸਲਾਹ ਬੁੱਕ ਕਰੋ",
    "nav.allPractice": "ਸਾਰੇ ਕਾਨੂੰਨੀ ਖੇਤਰ",
    "nav.attorneys": "ਵਕੀਲ",
    "hero.badge": "ਪ੍ਰਮੁੱਖ ਕਾਨੂੰਨੀ ਸਲਾਹ ਅਤੇ ਵਕਾਲਤ",
    "hero.title1": "ਅਧਿਕਾਰ। ਇਮਾਨਦਾਰੀ।",
    "hero.title2": "ਬਿਨਾਂ ਸਮਝੌਤੇ ਦੇ ਨਤੀਜੇ।",
    "hero.desc": "ਆਰਾਥਾਈ (ਏਕੇਐਮ ਐਸੋਸੀਏਟਸ) ਗੁੰਝਲਦਾਰ ਕਾਨੂੰਨੀ ਖੇਤਰਾਂ ਵਿੱਚ ਕਾਰਪੋਰੇਸ਼ਨਾਂ, ਸਟਾਰਟਅੱਪਾਂ ਅਤੇ ਪਰਿਵਾਰਾਂ ਦੀ ਪ੍ਰਤੀਨਿਧਤਾ ਕਰਦਾ ਹੈ। ਅਸੀਂ ਅਦਾਲਤਾਂ ਵਿੱਚ ਜਿੱਤ ਅਤੇ ਵਿਆਪਕ ਕਾਨੂੰਨੀ ਹੱਲ ਪ੍ਰਦਾਨ ਕਰਦੇ ਹਾਂ।",
    "hero.btnIntake": "ਗੁਪਤ ਸਲਾਹ ਦਾ ਸਮਾਂ ਤੈਅ ਕਰੋ",
    "hero.btnExplore": "ਕਾਨੂੰਨੀ ਖੇਤਰ ਦੇਖੋ",
    "stats.exp.val": "11+",
    "stats.exp.lbl": "ਸਾਲਾਂ ਦਾ ਸਰਗਰਮ ਅਨੁਭਵ",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "ਅਨੁਕੂਲ ਹੱਲ",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "ਕਾਰਪੋਰੇਟ ਅਤੇ ਨਿੱਜੀ ਗਾਹਕ",
    "stats.credentials.val": "ਉੱਚ ਸ਼੍ਰੇਣੀ",
    "stats.credentials.lbl": "ਲੀਗਲ ਬਾਰ ਪ੍ਰਮਾਣ ਪੱਤਰ",
    "home.practice.badge": "ਵਿਸ਼ੇਸ਼ ਕਾਨੂੰਨੀ ਖੇਤਰ",
    "home.practice.title": "ਕਾਨੂੰਨੀ ਖੇਤਰ",
    "home.practice.desc": "ਸਾਡੀ ਫਰਮ ਕਾਰਪੋਰੇਟ ਸ਼ਾਸਨ, ਜ਼ਮੀਨੀ ਮਾਲਕੀ ਆਡਿਟ ਅਤੇ ਅਦਾਲਤੀ ਵਕਾਲਤ ਨੂੰ ਉੱਚ ਮਿਆਰਾਂ 'ਤੇ ਸੰਤੁਲਿਤ ਕਰਦੀ ਹੈ।",
    "home.practice.all": "ਸਾਰੇ ਕਾਨੂੰਨੀ ਖੇਤਰ ਦੇਖੋ",
    "home.team.badge": "ਤਜਰਬੇਕਾਰ ਵਕੀਲ",
    "home.team.title": "ਮੁੱਢਲੇ ਭਾਗੀਦਾਰ",
    "home.team.desc": "ਵਿਸ਼ੇਸ਼ ਗਿਆਨ ਅਤੇ ਦਹਾਕਿਆਂ ਦਾ ਅਦਾਲਤੀ ਅਨੁਭਵ ਰੱਖਣ ਵਾਲੇ ਸਮਰਪਿਤ ਵਕੀਲ।",
    "home.team.viewProfile": "ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ",
    "home.team.all": "ਸਾਰੇ ਵਕੀਲਾਂ ਨੂੰ ਮਿਲੋ",
    "home.testimonials.badge": "ਗਾਹਕਾਂ ਦੀ ਰਾਏ",
    "home.testimonials.title": "ਆਗੂਆਂ ਦਾ ਵਿਸ਼ਵਾਸ",
    "contact.badge": "ਸਾਡੀਆਂ ਕਾਨੂੰਨੀ ਸੇਵਾਵਾਂ",
    "contact.title": "ਮਹੱਤਵਪੂਰਨ ਮੁਹਾਰਤ",
    "contact.office": "ਸ਼ਾਖਾ ਦਫ਼ਤਰ ਅਤੇ ਹੈਲਪਲਾਈਨ",
    "contact.officeDesc": "ਸਾਰੀਆਂ ਪੁੱਛਗਿੱਛਾਂ ਪੇਸ਼ੇਵਰ ਵਕੀਲ ਨਿਯਮਾਂ ਦੇ ਤਹਿਤ ਸਖਤੀ ਨਾਲ ਗੁਪਤ ਰੱਖੀਆਂ ਜਾਂਦੀਆਂ ਹਨ। ਸਾਡੇ ਦਫ਼ਤਰ ਆਓ ਜਾਂ ਹੈਲਪਲਾਈਨ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
    "contact.branchChennai": "ਮੁੱਖ ਦਫ਼ਤਰ (ਚੇਨਈ ਦਫ਼ਤਰ)",
    "contact.branchKarur": "ਸ਼ਾਖਾ ਦਫ਼ਤਰ (ਕਰੂਰ ਦਫ਼ਤਰ)",
    "contact.helpline": "ਐਮਰਜੈਂਸੀ ਕਾਨੂੰਨੀ ਹੈਲਪਲਾਈਨ",
    "contact.helplineDesc": "ਜ਼ਮਾਨਤ ਅਤੇ ਤੁਰੰਤ ਪੁਲਿਸ ਹਿਰਾਸਤ ਦੇ ਮਾਮਲਿਆਂ ਲਈ ਸਿੱਧਾ ਸੰਪਰਕ (24/7)",
    "contact.email": "ਈਮੇਲ ਪੁੱਛਗਿੱਛ",
    "contact.hours": "ਦਫ਼ਤਰ ਦਾ ਸਮਾਂ",
    "contact.hoursWeek": "ਸੋਮਵਾਰ - ਸ਼ੁੱਕਰਵਾਰ: ਸਵੇਰੇ 9:00 - ਸ਼ਾਮ 7:00",
    "contact.hoursSat": "ਸ਼ਨਿੱਚਰਵਾਰ: ਸਵੇਰੇ 10:00 - ਦੁਪਹਿਰ 2:00 (ਸਿਰਫ ਮੁਲਾਕਾਤ)",
    "contact.formTitle": "ਗੁਪਤ ਪੁੱਛਗਿੱਛ ਭੇਜੋ",
    "contact.name": "ਪੂਰਾ ਨਾਮ",
    "contact.emailAddr": "ਈਮੇਲ ਪਤਾ",
    "contact.phone": "ਫ਼ੋਨ ਨੰਬਰ",
    "contact.message": "ਸੁਨੇਹਾ / ਕੇਸ ਦੇ ਵੇਰਵੇ",
    "contact.btnSend": "ਸੁਨੇਹਾ ਭੇਜੋ",
    "contact.successTitle": "ਪੁੱਛਗਿੱਛ ਸਫਲਤਾਪੂਰਵਕ ਭੇਜੀ ਗਈ",
    "contact.successDesc": "ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਭੇਜਿਆ ਗਿਆ ਹੈ। ਸਾਡੇ ਇੱਕ ਸੀਨੀਅਰ ਭਾਗੀਦਾਰ 24 ਘੰਟਿਆਂ ਦੇ ਅੰਦਰ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰਨਗੇ।",
    "contact.btnAnother": "ਦੂਜਾ ਸੁਨੇਹਾ ਭੇਜੋ",
    "footer.desc": "ਆਰਾਥਾਈ (ਏਕੇਐਮ ਐਸੋਸੀਏਟਸ) ਕਾਰਪੋਰੇਟਾਂ, ਸੰਸਥਾਵਾਂ ਅਤੇ ਵਿਅਕਤੀਆਂ ਦੀ ਪ੍ਰਤੀਨਿਧਤਾ ਕਰਨ ਵਾਲੀ ਇੱਕ ਪ੍ਰਮੁੱਖ ਕਾਨੂੰਨੀ ਸਲਾਹਕਾਰ ਅਤੇ ਵਕਾਲਤ ਫਰਮ ਹੈ।",
    "footer.contact": "ਸੰਪਰਕ ਜਾਣਕਾਰੀ",
    "footer.rights": "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।",
    "footer.disclaimerTitle": "ਵਕੀਲ ਇਸ਼ਤਿਹਾਰਬਾਜ਼ੀ ਬੇਦਾਅਵਾ:",
    "footer.disclaimerText": "ਕੁਝ ਅਧਿਕਾਰ ਖੇਤਰਾਂ ਵਿੱਚ ਪੇਸ਼ੇਵਰ ਆਚਰਣ ਦੇ ਨਿਯਮਾਂ ਦੇ ਤਹਿਤ, ਇਸ ਸਾਈਟ ਦੀ ਸਮੱਗਰੀ ਨੂੰ ਵਕੀਲ ਦਾ ਇਸ਼ਤਿਹਾਰ ਮੰਨਿਆ ਜਾ ਸਕਦਾ ਹੈ। ਪਿਛਲੇ ਨਤੀਜੇ ਭਵਿੱਖ ਦੇ ਸਮਾਨ ਨਤੀਜਿਆਂ ਦੀ ਗਾਰੰਟੀ ਨਹੀਂ ਦਿੰਦੇ। ਸਲਾਹ ਬੁਕਿੰਗ ਨਾਲ ਕੋਈ ਕਾਨੂੰਨੀ ਸਬੰਧ ਨਹੀਂ ਬਣਦਾ।",
    "footer.privacy": "ਗੋਪਨੀਯਤਾ ਨੀਤੀ",
    "footer.terms": "ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ",
    "footer.disclaimer": "ਬੇਦਾਅਵਾ",
  },
  te: {
    "nav.home": "హోమ్",
    "nav.practiceAreas": "న్యాయ విభాగాలు",
    "nav.associates": "సహచరులు",
    "nav.caseResults": "కేసు ఫలితాలు",
    "nav.insights": "వ్యాసాలు & బ్లాగ్",
    "nav.aboutUs": "మా గురించి",
    "nav.contactUs": "సంప్రదించండి",
    "nav.bookConsultation": "సంప్రదింపుల బుకింగ్",
    "nav.allPractice": "అన్ని న్యాయ విభాగాలు",
    "nav.attorneys": "న్యాయవాదులు",
    "hero.badge": "అత్యుత్తమ న్యాయ సలహాలు & వాదాలు",
    "hero.title1": "అధికారం. నిబద్ధత.",
    "hero.title2": "రాజీలేని ఫలితాలు.",
    "hero.desc": "ఆరాథాయ్ (ఏకేఎం అసోసియేట్స్) కార్పొరేషన్లు, స్టార్టప్‌లు మరియు కుటుంబాల క్లిష్టమైన న్యాయ విఫలాలను సమర్థవంతంగా నిర్వహిస్తుంది. మేము కోర్టులలో విజయాలు మరియు పూర్తి న్యాయ సలహాలను అందిస్తాము.",
    "hero.btnIntake": "సమావేశ సమయం కేటాయించండి",
    "hero.btnExplore": "న్యాయ విభాగాలను పరిశీలించండి",
    "stats.exp.val": "11+",
    "stats.exp.lbl": "సంవత్సరాల ప్రత్యక్ష అనుభవం",
    "stats.settle.val": "98%",
    "stats.settle.lbl": "అనుకూలమైన పరిష్కారాలు",
    "stats.clients.val": "5,000+",
    "stats.clients.lbl": "కార్పొరేట్ మరియు ప్రైవేట్ క్లయింట్లు",
    "stats.credentials.val": "అత్యున్నత శ్రేణి",
    "stats.credentials.lbl": "లీగల్ బార్ అర్హతలు",
    "home.practice.badge": "ప్రత్యేక న్యాయ విభాగాలు",
    "home.practice.title": "న్యాయ విభాగాలు",
    "home.practice.desc": "మా సంస్థ కార్పొరేట్ పాలన, భూమి పత్రాల ఆడిట్ మరియు కోర్టు వాదనలను అత్యున్నత ప్రమాణాలతో నిర్వహిస్తుంది.",
    "home.practice.all": "అన్ని న్యాయ విభాగాలను చూడండి",
    "home.team.badge": "అనుభవజ్ఞులైన న్యాయవాదులు",
    "home.team.title": "ప్రధాన భాగస్వాములు",
    "home.team.desc": "ప్రత్యేక పరిజ్ఞానం మరియు దశాబ్దాల కోర్టు అనుభవం కలిగిన అంకితభావం గల న్యాయవాదులు.",
    "home.team.viewProfile": "ప్రొఫైల్ చూడండి",
    "home.team.all": "న్యాయవాదులందరినీ కలవండి",
    "home.testimonials.badge": "క్లయింట్ల అభిప్రాయాలు",
    "home.testimonials.title": "నాయకుల నమ్మకం",
    "contact.badge": "మా న్యాయ సేవలు",
    "contact.title": "కీలకమైన నైపుణ్యం",
    "contact.office": "బ్రాంచ్ ఆఫీసులు & హెల్ప్‌లైన్",
    "contact.officeDesc": "అన్ని విచారణలు వృత్తిపరమైన న్యాయవాది నిబంధనల ప్రకారం ఖచ్చితంగా రహస్యంగా ఉంచబడతాయి. మా కార్యాలయాన్ని సందర్శించండి లేదా హెల్ప్‌లైన్‌ను సంప్రదించండి.",
    "contact.branchChennai": "ప్రధాన కార్యాలయం (చెన్నై ఆఫీస్)",
    "contact.branchKarur": "బ్రాంచ్ ఆఫీస్ (కరూర్ ఆఫీస్)",
    "contact.helpline": "అత్యవసర న్యాయ హెల్ప్‌లైన్",
    "contact.helplineDesc": "బెయイルస్ మరియు అత్యవసర పోలీస్ కస్టడీ కేసుల కోసం నేరుగా సంప్రదించండి (24/7)",
    "contact.email": "ఈమెయిల్ సంప్రదింపులు",
    "contact.hours": "కార్యాలయ వేళలు",
    "contact.hoursWeek": "సోమవారం - శుక్రవారం: ఉదయం 9:00 - సాయంత్రం 7:00",
    "contact.hoursSat": "శనివారం: ఉదయం 10:00 - మధ్యాహ్నం 2:00 (అపాయింట్‌మెంట్ మాత్రమే)",
    "contact.formTitle": "రహస్య సమాచారం పంపండి",
    "contact.name": "పూర్తి పేరు",
    "contact.emailAddr": "ఈమెయిల్ చిరునామా",
    "contact.phone": "ఫోన్ నంబర్",
    "contact.message": "సందేశం / కేసు వివరాలు",
    "contact.btnSend": "సందేశం పంపండి",
    "contact.successTitle": "సమాచారం విజయవంతంగా పంపబడింది",
    "contact.successDesc": "మీ సందేశం సురక్షితంగా పంపబడింది. మా సీనియర్ భాగస్వామి ఒకరు 24 గంటలలోపు మిమ్మల్ని సంప్రదిస్తారు.",
    "contact.btnAnother": "మరో సందేశం పంపండి",
    "footer.desc": "ఆరాథాయ్ (ఏకేఎం అసోసియేట్స్) కార్పొరేట్లు, సంస్థలు మరియు వ్యక్తులకు ప్రాతినిధ్యం వహించే ప్రముఖ న్యాయ సలహాలు & వాదాల సంస్థ.",
    "footer.contact": "సంప్రదింపు సమాచారం",
    "footer.rights": "సర్వ హక్కులు ప్రత్యేకించబడినవి.",
    "footer.disclaimerTitle": "న్యాయవాది ప్రకటన నిరాకరణ:",
    "footer.disclaimerText": "కొన్ని న్యాయ పరిధులలో వృత్తిపరమైన ప్రవర్తనా నియమాల ప్రకారం, ఈ సైట్‌లోని కంటెంట్ న్యాయవాది ప్రకటనగా పరిగణించబడవచ్చు. మునుపటి ఫలితాలు భవిష్యత్తులో అదే విధమైన ఫలితాలకు హామీ ఇవ్వవు. సంప్రదింపుల బుకింగ్‌లు న్యాయవాది-క్లయింట్ సంబంధాన్ని ఏర్పరచవు.",
    "footer.privacy": "గోప్యాదా విధానం",
    "footer.terms": "సేవా నిబంధనలు",
    "footer.disclaimer": "నిరాకరణ",
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app_lang");
    const allowed: Language[] = ["en", "ta", "hi", "as", "bn", "gu", "kn", "ml", "mr", "or", "pa", "te"];
    return allowed.includes(saved as Language) ? (saved as Language) : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key: string): string => {
    const dict = translations[language] || translations["en"];
    return dict[key] || translations["en"][key] || key;
  };

  const tText = (en: string, ta?: string, hi?: string): string => {
    if (language === "ta" && ta) return ta;
    if (language === "hi" && hi) return hi;
    return en;
  };

  return (
    <LanguageContext.Provider value={{ language, selectedLanguage: language, setLanguage, t, tText }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
